version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "verkundenbot-fan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18hy39250eplj"
s3_prefix = "verkundenbot-fan"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "verkundenbot-fan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-164l6bb14wjq2"
s3_prefix = "verkundenbot-fan"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
profile = "glolabs"
